version: '3.7'
services:
    api:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./:/dapp
        ports:
            - "8012:8012"
        depends_on:
            - api-php-fpm
            - api-php-cli
        restart: unless-stopped

    api-php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_IDE_CONFIG: serverName=API
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USER: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME:  ${DB_DATABASE}
            FRONTEND_URL: http://localhost:8011
        depends_on:
            - api-postgres
        volumes:
            - ./:/dapp

    api-php-cli:
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USER: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME:  ${DB_DATABASE}
            FRONTEND_URL: http://localhost:8011
        depends_on:
            - api-postgres
        volumes:
            - ./:/dapp

    api-postgres:
        image: postgres:16.1-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
          - '54322:5432'
        volumes:
          - api-postgres:/var/lib/postgresql/data

volumes:
    api-postgres: ~
